### ISSUE TITLE
Reduce data consumption of Dataset tests

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/good-pdc#7]
Currently, the Dataset Analysis test downloads the entire file content of all public PDC Datasets, roughly 9.5GB/every three hours. The datasets are deleted after analysis; but this puts a large strain on CMS servers. 

## Tasks

- [x] Transition dataset_report to use HTTP HEAD requests to get metadata without downloading the entire file
- [x] Download only the necessary part of the file to analyze the headers and a few rows for statistics
- [x] Add data consumption log message and tracker for both archive_report and dataset_report modules on both the file and workflow level

**Comment by grugnog** [comment]
See #8

**Comment by TheBoatyMcBoatFace** [comment]
Closed by #8
